### ISSUE TITLE
 Error occurred while enabling FlashlightPlus v1.0.10

### ISSUE THREAD

**Issue by TheChampTF** [MattsLab/FlashlightPlus#5]
[19:30:18] [Server thread/INFO]: [FlashlightPlus] Enabling FlashlightPlus v1.0.10
[19:30:18] [Server thread/INFO]: [FlashlightPlus] Please report any issues with this plugin to:
[19:30:18] [Server thread/INFO]: [FlashlightPlus] https://github.com/FallenYouth/FlashlightPlus/issues/new
[19:30:18] [Server thread/ERROR]: Error occurred while enabling FlashlightPlus v1.0.10 (Is it up to date?)
java.lang.NullPointerException
	at com.fallenyouth.FlashlightPlus.FlashlightPlus.onEnable(FlashlightPlus.java:51) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Bukkit-4a7472d]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Bukkit-4a7472d]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins_1.8.8.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-4a7472d]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342) [craftbukkit.jar:git-Bukkit-4a7472d]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314) [craftbukkit.jar:git-Bukkit-4a7472d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406) [craftbukkit.jar:git-Bukkit-4a7472d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370) [craftbukkit.jar:git-Bukkit-4a7472d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit.jar:git-Bukkit-4a7472d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235) [craftbukkit.jar:git-Bukkit-4a7472d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) [craftbukkit.jar:git-Bukkit-4a7472d]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by MattsLab** [comment]
What version of Java are you running?

**Comment by TheChampTF** [comment]
Java 8 Update 45

**Comment by MattsLab** [comment]
I see that the plugin is slightly out of date, the releases for it are here https://github.com/MattsLab/FlashlightPlus/releases

**Comment by TheChampTF** [comment]
Oh, why not post on spigot any more?

**Comment by MattsLab** [comment]
I want to add more content to the plugin before doing the final 1.0.11 update.

**Comment by TheChampTF** [comment]
Yea okay (:

**Comment by MattsLab** [comment]
Did that solve the issue?

**Comment by TheChampTF** [comment]
Looks fixed for now, of what I can see no problems (:

Thanks!
